export const castle2Examples = [
  [
    ["REI1431", "START", "", ""],
    ["", "LD", "GR1,M", ""],
    ["", "LD", "GR2,N", ""],
    ["", "ST", "GR1,MWK", ""],
    ["", "ST", "GR2,NWK", ""],
    ["LOOP1", "LD", "GR1,MWK", ""],
    ["", "LD", "GR2,NWK", ""],
    ["LOOP2", "CPA", "GR1,GR2", ""],
    ["", "JZE", "OWARI", ""],
    ["", "JMI", "NEXT", ""],
    ["", "SUBA", "GR1,GR2", ""],
    ["", "JUMP", "LOOP2", ""],
    ["NEXT", "ST", "GR1,NWK", ""],
    ["", "ST", "GR2,MWK", ""],
    ["", "JUMP", "LOOP1", ""],
    ["OWARI", "ST", "GR2,GCM", ""],
    ["", "RET", "", ""],
    ["M", "DC", "64", ""],
    ["N", "DC", "24", ""],
    ["MWK", "DS", "1", ""],
    ["NWK", "DS", "1", ""],
    ["GCM", "DS", "1", ""],
    ["", "END", "", ""],
  ],
  [
    ["REP2", "START", "", ""],
    ["", "LAD", "GR1, 0", ""],
    ["", "LAD", "GR2, 0", ""],
    ["LOOP", "CPA", "GR1, SIZE", ""],
    ["", "JZE", "FIN", ""],
    ["", "LD", "GR0, NUM, GR1", ""],
    ["", "LD", "GR3, GR0", ""],
    ["", "AND", "GR3, =#0001", ""],
    ["", "JZE", "SKIP", ""],
    ["", "ST", "GR0, NUM, GR2", ""],
    ["", "LAD", "GR2, 1, GR2", ""],
    ["SKIP", "LAD", "GR1, 1, GR1", ""],
    ["", "JUMP", "LOOP", ""],
    ["FIN", "RET", "", ""],
    ["NUM", "DC", "11, 2, 36, 3, 4", ""],
    ["SIZE", "DC", "5", ""],
    ["", "END", "", ""],
  ]
];
